version: "3.8"

services:
    application: 
        build: .
        command: ["npm", "start"]
        ports: 
            - "3000:3000"
            - "2000:2000"
        restart: always
        volumes:
            - .:/usr/app
